### PR TITLE
Rename some variables to make scoping more clear

### PR DESCRIPTION
**Pull request by jrobeson**

### CODE REVIEW

**Comment by jrobeson** [comment]
I ran into these while trying some automatic transformations.

**Comment by jrobeson** [comment]
This test failure shows that nothing is actually using the name variable in the signal section. It just kinda ends. https://github.com/sidorares/dbus-native/blob/master/lib/introspect.js#L190

**Comment by jrobeson** [comment]
@sidorares : so what's the deal with that signal section?

**Comment by sidorares** [comment]
it feels like it's mapping of remote signals from object introspection data. Can you try to check that we don't have that already? If so would be good to add

**Comment by sidorares** [comment]
Do you need example xml with signals?

**Comment by jrobeson** [comment]
I'm just trying to make sure I can just delete the code that handles signals in introspec.js because it doesn't seem to be doing anything and causes an eslint issue.

If this is a purely missing feature then a bug should be filed.   Can you file said bug? 

I got involved in this project to learn dbus and practice JS, so I think you'd do a better job at explaining it.

**Comment by jrobeson** [comment]
I should be clearer and say that i don't think the code currently does anything, but somehow maybe it does?

**Comment by sidorares** [comment]
no, at the moment does nothing. Ok to remove it unless you have time to add signals code straight away

**Comment by jrobeson** [comment]
I"m having trouble wrapping my mind around some of the techniques so I'd like to continue cleaning things up before adding anything new.

**Comment by jrobeson** [comment]
uggh.. some of my let experiments crept into this, so i'm gonna have to revert those.

**Comment by jrobeson** [comment]
all good now!

**Pull request merged**
