### PR TITLE
Move all let back to var for node 4.x compatibility

### PR DESCRIPTION
**Pull request by jrobeson**

### CODE REVIEW

**Comment by jrobeson** [comment]
These were in the codebase before my initial (and reverted) var to let commit.

**Comment by pabigot** [comment]
The use of `let` in the examples was (is) correct, as the examples use strict mode.  Switching them to `var` is not correct.

**Comment by jrobeson** [comment]
i removed the strict mode from the examples before didn't i?

**Comment by jrobeson** [comment]
I did in https://github.com/sidorares/dbus-native/commit/50c28818cc07a0aa618287054c926f18a889a9d8#diff-bfebe34154a0dfd9fc7b447fc9ed74e9

I messed up by not removing the lets from some of the examples. I didn't try them all at the time. :(

**Comment by jrobeson** [comment]
I was going to add `use strict';` to other files so we could use `let` and `const` in the rest of the codebase  but @sidorares was against it. I decided to remove all `use strict;` for consistency reasons at that ponit.

**Comment by pabigot** [comment]
I didn't see 50c2881, but the change is still not complete.  At current master 352e78c the `basic-client` and `client-signals` still fail under Node 4 because of top-level `let`s.  Other examples fail because of arrow functions (work under Node 4 with strict) or spread syntax (does not work under Node 4 at all).

If @sidorares felt that the library code should avoid `'use strict'` for compatibility reasons that seems justifiable, but I personally always use it and don't see that requiring examples be constrained to the features from JavaScript's browser-only days adds value.

**Comment by jrobeson** [comment]
I was under the impression that top level lets should work because top level consts do.  the arrow functions and spread syntax are  of course another story.

**Comment by jrobeson** [comment]
You're right about the lets. I should have removed them too. consts do work

**Comment by jrobeson** [comment]
the lets are fixed in https://github.com/sidorares/dbus-native/pull/212 . They can easily be converted to const.

**Comment by jrobeson** [comment]
I'm gonna have to configure eslint to properly catch these for the future.

**Comment by jrobeson** [comment]
Arrow functions seem fine in node 4.x. so it's really only the spread syntax.

**Comment by jrobeson** [comment]
@pabigot : can you tell me where you're seeing arrow functions fail in 4.x?

**Comment by pabigot** [comment]
You're right; it appears Node 4.5 (at least) accepts arrow functions in non-strict code.

basic-client failed under master without the other patch in my #209 PR; I've rebased that, and it now fails for other reasons.

    lilith[394]$ node --stack-trace-limit=100 examples/basic-client.js 
    /mnt/devel/external/Node/node-dbus/node_modules/xml2js/lib/xml2js.js:216
              throw ex;
              ^
    
    TypeError: Cannot redefine property: Flag
        at Function.defineProperty (native)
        at addReadProp (/mnt/devel/external/Node/node-dbus/lib/introspect.js:143:22)
        at /mnt/devel/external/Node/node-dbus/lib/introspect.js:180:13

I'm going back to 0.2.3; master is far too unstable for me to work with at this time.

**Pull request merged**
