### PR TITLE
Add eqeqeq eslint rule

### PR DESCRIPTION
**Pull request by jrobeson**

### CODE REVIEW

**Comment by jrobeson** [comment]
Stuff i didn't commit keeps getting added, so this can't be merged yet.

**Comment by jrobeson** [comment]
I think it should be good now

**Comment by jrobeson** [comment]
Are you cool with this after I fix the conflict?

**Comment by pabigot** [comment]
This broke introspect at lines 30..31:

    f2c1667c (johnny          2017-10-05 06:51:17 -0400  30)         var xmlnodes = result['node'];
    2cad7bd1 (johnny          2017-10-17 04:29:06 -0400  31)         if (xmlnodes === null) xmlnodes = [];

The former check `xmlnodes == null` worked since `xmlnodes` might be `undefined`.

I expect to do a PR that includes a fix for this one, but there may be others like it that remain undiscovered.

**Pull request merged**
