### PR TITLE
add support for marshalling 64-bit integer values

### PR DESCRIPTION
**Pull request by egasimus**
using https://www.npmjs.com/package/long

### CODE REVIEW

**Comment by sidorares** [comment]
Hi! Thanks for this. What do you think about exporting Long ( directly or via some helpers ) so users of dbus library don't need to require their own Long module instance

I was thinking to add "create[Type]" helpers anyway, do you have any opinion on what api should be?

```js
dbus.createVariant(value, optional_signature); // if no signature have it automatic based on what is in value
dbus.createArray([val1, val2, val3, val4], element_signature); // probably make signature required. Could use first element type, but what if input is empty array?
dbus.createUInt64('number_as_string');
dbus.createInt64('number_as_string');
```

something like this?

**Comment by egasimus** [comment]
Looks good imho.

**Comment by sidorares** [comment]
@egasimus could you have a look at failing tests? ( and maybe add `dbus.createUInt64('number_as_string'); dbus.createInt64('number_as_string');` wrappers )

**Comment by jrobeson** [comment]
Is this PR relevant anymore?

**Comment by sidorares** [comment]
I think it is not relevant due to #152

**Pull request closed without merging**
